### ISSUE TITLE
Error on classic era (hardcore)

### ISSUE THREAD

**Issue by aglarcz** [RestedXP/RXPGuides#189]
![image](https://github.com/RestedXP/RXPGuides/assets/17107410/9de973dc-1773-4500-848b-ff6914e2fbdd)
Any ideas how to fix?

**Comment by Morynne** [comment]
It's not reallly an issue. It's the way how works rare scanning on classic era

**Comment by SabreValkyrn** [comment]
https://discord.com/channels/826162743669162034/840629461312864278/1057444249790054440

`ADDON_ACTION_FORBIDDEN` / "TargetUnit()" Error is caused by "Only show when in range" target scanning.

If you already use BugSack, ensure crashes are muted.

If you use Narcissus, install BugSack to prevent the days since last error popup

To disable this error entirely, go to Settings -> Targeting -> "Only show when in range".
