### ISSUE TITLE
Stuck at Retrieving quest data

### ISSUE THREAD

**Issue by atstoyanov** [RestedXP/RXPGuides#214]
Every guide is stuck at 'Retrieving quest data...' after logging in with a character. Often the UI reload helps. Clearing cache folders didn't help.
<img width="210" alt="image" src="https://github.com/RestedXP/RXPGuides/assets/3524687/2925ce5b-f047-4eca-8098-d2aad676ae21">

**Comment by Zarant** [comment]
The data is being retrieved from the server, the amount of data retrieval requests you can make is limited, if the request rate exceeds a certain amount the server just stop answering the client's requests. The addon makes sure to throttle the requests to avoid being locked out of it. If you get to the point where the server stopped answering the requests, UI reloads won't help, you have to relog when that happens.

Most of the time this error happens when you have other addons doing the same kind of thing in the background, the only way around this would be to have an internal database with the quest data cached (just like Questie does). But that goes beyond the scope of this project, I added questie compatibility a while ago, so if that problem persist you can try installing Questie alongside RXPGuides, that will likely solve this issue.

**Comment by Zarant** [comment]
Also please note that when you first open a guide, it takes a few minutes until all the quest retrieval requests are processed and cached, so if you skip around steps too much you'll run into this issue. Which it's unlikely to happen when you're just playing through it normally instead of looking up ahead before the guide is fully loaded.

**Comment by atstoyanov** [comment]
I've tested with RXP being the only addon loaded. Hit the issue again, but less often. Opening the quest log helps even without questie.

**Comment by atstoyanov** [comment]
I have this issue on WOTLK Classic. I haven't tested it on Classic. 
When quests are collapsed in the quest log the RestedXP guide shows `Retrieiving quest data...`. After the quest log is opened and the tree is expanded the RestedXP Shows correct information about this quest.

<img width="856" alt="Screenshot 2024-01-30 105308" src="https://github.com/RestedXP/RXPGuides/assets/3524687/9ecddb9e-1dbb-4eb2-b6fd-10d4697dade2">
<img width="854" alt="Screenshot 2024-01-30 105318" src="https://github.com/RestedXP/RXPGuides/assets/3524687/89d6432e-a457-4e67-8cd1-253c4d7c961a">

Some addons like `Leatrix Plus` can Enhance the quest log and add the `Collapse/Expand All` button and they might collapse the whole list when the list is not opened. 
I'm not sure if this is native behaviour, but quest log zones are collapsed or expanded based on your current location. This explains why changing the zone shows the `Retrieiving quest data...` instead of the progress.

**Comment by Zarant** [comment]
Yeah this is likely the culprit, the only way around this would be overriding these settings and always expand the quest log if the quest is not cached.

**Comment by Starlynk1** [comment]
Just saw this issue and tested it since I use Leatrix as well. Having the quest logs collapsed and opening new guides, it appears that RXP now opens all of the quests that are collapsed when it reaches a point that it needs to cache quest data. I could not reproduce the issue as of the latest Alpha build.
